// Generated by https://quicktype.io

export interface BusquedaGeneral {
    ok:            boolean;
    message:       string;
    ambulancia:    Ambulancia[];
    rayosX:        any[];
    ultrasonido:   Ultrasonido[];
    otrosServicio: any[];
    endoscopia:    Endoscopia[];
    laboratorios:  Laboratorio[];
    tomografia:    Tomografia[];
}

export interface Ambulancia {
    name:               string;
    _id:                string;
    DESTINO:            string;
    PRECIODIA:          string;
    REDONDODIA:         string;
    PRECIONOCHE:        string;
    PRECIOREDONDONOCHE: string;
    __v:                number;
}

export interface Endoscopia {
    _id:                      string;
    PROCEDIMIENTO:            string;
    PUBLICO:                  string;
    MEMBRESIA:                string;
    SEGUROLABORAL:            string;
    DIFERENCIAPERSONASINYCON: string;
    __v:                      number;
}

export interface Laboratorio {
    _id:                string;
    ESTUDIO:            string;
    MUESTRA:            string;
    ENTREGA:            string;
    MICRO?:             string;
    PUBLICO:            string;
    COSTO:              string;
    H:                  string;
    B:                  string;
    URGENCIA_PUB?:      string;
    C:                  string;
    H6:                 string;
    B6?:                string;
    MEMBRESIA:          string;
    C5:                 string;
    H5:                 string;
    B5:                 string;
    URGENCIA_MEM?:      string;
    C4:                 string;
    H4:                 string;
    B4:                 string;
    PROMOCION:          string;
    C2:                 string;
    H2:                 string;
    B2:                 string;
    NOCTURNO:           string;
    C3:                 string;
    H3?:                string;
    B3:                 string;
    URGENCIAPUBLICO?:   string;
    URGENCIAMEMBRESIA?: string;
    __v?:               number;
}

export interface Tomografia {
    _id:         string;
    ESTUDIO:     string;
    PUBLICO:     string;
    MEMBRESIA:   string;
    URGENCIAPUB: string;
    URGENCIAMEM: string;
    NOCHEPUB:    string;
    NOCHEMEM:    string;
    __v:         number;
}

export interface Ultrasonido {
    name:                   string;
    _id:                    string;
    ULTRASONIDO:            string;
    INDICACIONES:           string;
    PRECIO_PUBLICO:         string;
    PRECIO_URGENTE:         string;
    HOSP_DENTRO_DE_HORARIO: string;
    HOSP_URGENTE:           string;
    PAGO_AL_DOC_URGENCIAS:  string;
    __v?:                   number;
}
