// Generated by https://quicktype.io


export interface Examen {
    _id:               string;
    ESTUDIO:           string;
    MUESTRA:           string;
    ENTREGA:           string;
    PUBLICO:           string;
    COSTO:             string;
    H:                 string;
    B:                 string;
    URGENCIAPUBLICO:   string;
    C:                 string;
    H6:                string;
    MEMBRESIA:         string;
    C5:                string;
    H5:                string;
    B5:                string;
    URGENCIAMEMBRESIA: string;
    C4:                string;
    H4:                string;
    B4:                string;
    PROMOCION:         string;
    C2:                string;
    H2:                string;
    B2:                string;
    NOCTURNO:          string;
    C3:                string;
    B3:                string;
    __v:               number;
}
