export class Paciente {

  constructor(

  public nombrePaciente?: string,
  public apellidoPaterno?: string,
  public apellidoMaterno?: string,
  public fechaNacimientoPaciente?: string,
  public entidadNacimiento?: string,
  public edad?: number,
  public curp?: string,
  public pais?: string,
  public telefono?: number,
  public contactoEmergancia?: string,
  public telefonoEmergencia?: string,
  public correo?: string,
  public cpPaciente?: string,
  public paisPaciente?: string,
  public municipioPacienye?: string,
  public estadoPaciente?: string,
  public poblacion?: string,
  public calleNumeroPaciente?: string,
  public referenciaPaciente?: string,
  public nombreRazonSocial?: string,
  public entidadFederativa?: string,
  public coloniaFiscal?: string,
  public RFCFiscal?: string,
  public municipioFiscal?: string,
  public cpFiscal?: string,
  public localidadFiscal?: string,
  public emailFiscal?: string,
  public nombreRazonSocial2?: string,
  public entidadFederativa2?: string,
  public coloniaFiscal2?: string,
  public RFCFiscal2?: string,
  public municipioFiscal2?: string,
  public cpFiscal2?: string,
  public localidadFiscal2?: string,
  public emailFiscal2?: string,
  public nombreRazonSocial3?: string,
  public entidadFederativa3?: string,
  public coloniaFiscal3?: string,
  public RFCFiscal3?: string,
  public municipioFiscal3?: string,
  public cpFiscal3?: string,
  public localidadFiscal3?: string,
  public emailFiscal3?: string
  ) {

  }
}
