// Generated by https://quicktype.io

export interface PaquetesDB {
    
    nombrePaquete:        string;
    costoTotal:           number;
    consultasGinecologia: number;
    examenesLaboratorio:  string[];
    CitasIncluidas:       string[];
    icon:                 string;
}
