// Generated by https://quicktype.io

export interface PedidosLaboratorio {
    ok:       boolean;
    message:  string;
    estudios: PedidosLaboratorioEstudio[];
}

export interface PedidosLaboratorioEstudio {
    estadoPedido: string;
    estudios:     EstudioEstudio[];
    _id:          string;
    nombre:       string;
    edad:         number;
    sexo:         string;
    total:        number;
    __v:          number;
}

export interface EstudioEstudio {
    nombreEstudio: string;
    precioSin:     string;
    precioCon:     string;
    entrega:       string;
    idEstudio:     string;
}
